### ISSUE TITLE
Soul Calibur 5 RAP file not downloading.

### ISSUE THREAD

**Issue by Tritium-X** [yne/psndl#1]
When I typed in Soul Calibur 5 into the list I downloaded the game and have all the necessary files EXCEPT for the RAP file which does not work when I click on "RAP" next to the game.  Is it broken and if so?  Can it be fixed?

**Comment by yne** [comment]
What is your browser ?
Works fine here (Chromium)

**Comment by Tritium-X** [comment]
Microsoft Edge, I tried it on Chrome and now it works.

**Comment by Tritium-X** [comment]
Another question I have is I installed the add-ons and the game and the rap and pkg files are where they should be, however when I try to launch the game I get an error, saying that it could not load.  I deleted the main game file so i'll have to redownload it, but I followed exactly everything in this video.
Instead of using psndl to get the game files I used your site since their website was down.

https://www.youtube.com/watch?v=upR7J3U9_PI

**Comment by yne** [comment]
I never used psndl nor RPCS3 so I can't help you.
I can only help you if you have issue on my project (but the PKG works and the RAP work too ).
Try to explain the situation on a PS3-related forum and give them your search (http://yne.fr/PSN/#Calibur) so they can try it and help you.

**Comment by Tritium-X** [comment]
Ok, thanks will head over there.
