### ISSUE TITLE
Missing PKGs

### ISSUE THREAD

**Issue by Radu13** [yne/psndl#3]
Hello I really appreciate this ps3 pkg database, however I can't find the preorder bonus .pkg for ratchet and clank into the nexus and the enhanced characters .pkg for dragon ball raging blast 2.
There is a discord or something like that where people can talk about and organize all those packages, if someone dumped them,  and eventually upload them on the database? Or maybe you know guys who aalready has a big .pkg archive with those in it actually.

**Comment by yne** [comment]
I tried my best to collect them all, but if you find the missing one give me a sign so I can add them to the database

**Comment by Radu13** [comment]
Which ones you managed to find?

**Comment by yne** [comment]
I've added around 700 new pkg from https://psndl.net/download-db 7 month ago
The rest is from the PSNstuff app I used in 2015

https://yne.fr/psndl/#nexus

**Comment by yne** [comment]
Do not hesitate to open if there any other missing urls
