### ISSUE TITLE
Database not compatible with PS3 web browser

### ISSUE THREAD

**Issue by LuanTeles** [yne/psndl#5]
Can you make it compatible with ps3 web browser? 

http://psndl.byethost7.com/controller/contents.php was the only one that worked on ps3 web browser,  but the site recently got shutted down.

**Comment by yne** [comment]
I don't have a PS3 to test with, but IIRC the PS3 browser can only save into an USB mass storage, meaning that only <4GB package can be saved/installed.

What error is displayed ?

The repo now automatically also generate a PKGI [config.txt](https://yne.fr/psndl/config.txt) and associated databases that you could also use

**Comment by LuanTeles** [comment]
HEN and Most of CFW have the download_list.xml modded that allow us to save files to internal/external storages and most of the users downloads things to the internal hdd with no file size restrictions.

The web page simple doesnt work, ps3 only supports html and basic css not css3

![image](https://user-images.githubusercontent.com/110236244/230979719-0c3b6764-47df-475c-9062-6db400056190.png)

**Comment by yne** [comment]
Hi, I fixed the page for both Silk and Webkit engine.

But I did not found a way to download JS-generated RAP using `data:` URI.

If you have a working example of `<a href="data:....">download</a>` links that work on PS3 I'll gladly fix that.

I'll let you close this issue if the fix is okay for you

**Comment by yne** [comment]
No reply so I guess it's okay

**Comment by LuanTeles** [comment]
OH sorry i didn't see that you replied.

Yeap, now it is displaying correctly :) thanks
