### ISSUE TITLE
[Feature Request] Filter

### ISSUE THREAD

**Issue by LuanTeles** [yne/psndl#6]
Can content filter be added, to show only games, dlcs, avatars and etc?

Or at least Alphabetical Order

**Comment by yne** [comment]
> Can content filter be added

current db.csv is not fully tagged (game, tool, DLC ....)

> Or at least Alphabetical Order

PS3 Silk engine don't have `.sort()` method... so this may be tricky

I'll keep this Issue open so I'll remember to tag all entries

**Comment by yne** [comment]
@LuanTeles I've added a name sorting function. But I don't have a PS3 to check.

Can you confirm ?
