### ISSUE TITLE
[Feature Request] RAP download on PS3

### ISSUE THREAD

**Issue by LuanTeles** [yne/psndl#8]
https://nopaystation.com/search?query=&platform=ps3&limit=10&orderBy=completionDate&sort=DESC&missing=Show CAN download raps to the PS3, maybe you can take a look at it.

**Comment by yne** [comment]
I have 2 options :

- rely on they server (example : https://nopaystation.com/tools/rap2file/EP0082-NPEB00254_00-INFINITYMAINGAME/bb369366ecfc92555bdb9954d18db40f)
- pre-generate all RAP file during github pages deployment 

I think i'll try the last option to stay independent from external server
